benchmarks:
- curl_curl_fuzzer_http
- harfbuzz-1.3.2
- jsoncpp_jsoncpp_fuzzer
- lcms-2017-03-21
- libjpeg-turbo-07-2017
- libpcap_fuzz_both
- libpng-1.2.56
- libxml2-v2.9.2
- libxslt_xpath
- mbedtls_fuzz_dtlsclient
- openssl_x509
- openthread-2019-12-23
- php_php-fuzz-parser
- proj4-2017-08-14
- re2-2014-12-09
- sqlite3_ossfuzz
- systemd_fuzz-link-parser
- vorbis-2017-12-11
- woff2-2016-05-06
- zlib_zlib_uncompress_fuzzer
cloud_compute_zone: us-central1-b
cloud_project: fuzzbench
cloud_sql_instance_connection_name: fuzzbench:us-central1:postgres-experiment-db=tcp:5432
concurrent_builds: null
custom_seed_corpus_dir: null
description: null
docker_registry: us-central1-docker.pkg.dev/fuzzbench/fuzzbench-private
experiment: 2022-08-12-14-04-30m-dongge
experiment_filestore: gs://fuzzbench-data-private
fuzzers:
- centipede
- libfuzzer
git_hash: c118d449c0ce3e94f9597b4a807b841b33e23b67
local_experiment: false
max_total_time: 1900
measurers_cpus: null
merge_with_nonprivate: false
no_dictionaries: false
no_seeds: false
oss_fuzz_corpus: false
preemptible_runners: false
private: true
region_coverage: false
report_filestore: gs://fuzzbench-reports-private
runner_machine_type: n1-standard-1
runner_memory: 12GB
runner_num_cpu_cores: 1
runners_cpus: null
snapshot_period: 900
trials: 1
